language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE travis_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: dkqCZXjXUbVsm+s+wyw5fSYtZCbWCbButJcZWVC9jET8f5G3aD3TQ1KK/0D2bQtv6OnIqwy3867WALFjC7KnZBvhJorNqJ5Y2o+nmPPWb4E6vHLlQpQ60zs+SQ+AVqlT9jM6nC+3G9NuGJ75I8NtRINctG9RR/BJT59wqF7Q9ZV2aBoxjsHAOH5rjgIdWey6y6jA2mdxdrI5bYtgpdTHpf4YRRM9SFf1UCbceNOj6a/vJBr6FCtSyu6aj1Oc/B6VQtL4YByVDtVLmOBBhIXZ+EzfQOma1/+Q+Ty2u8J0ujgcdcYP+HE5asusYWqtJxvfqUW+dKofiscGzmMD4LxnMmgXv3OkREmhaFKS4mvU7ILQ3E5vjhOkPUvKxlLZMCxG/0VaVxokhuVjfafDW9qxw/I3v2sg0FuiBkeXIG3VbfBoTLg+BueZwpP6mnWH6bBil+9e3ApYAO2/OSWxWrFljhtD5wj7lUciOMhJcDJksFJM/K9VYfU2KoRoVHIvqWoD+0GebEarVu720P/G5sx020u4+N/C3nxKc6nCCxmd6IJlVjA6rEJmfWaka1it2H3aFgnbNoSD495X8JkqNQCi6xojd2w1j1HEw4GEfu3J1m49AwNCrpAtlbBNx6c4vwm1xFVpoSix0vhidJhmdYEZw+iJYoD6gQ0L9KjmuwPFjgI=
    app: joel-palette-picker
    skip_cleanup: true